### ISSUE TITLE
Removal of master branch from github

### ISSUE THREAD

**Issue by lerwys** [lnls-sirius/epics-dev#10]
I would like to remove the "master" branch from this repository, as it does not make much sense, since we have multiple "master branches", differing from the epics-base version supported.

I would also make the base-3.15 our default branch in github.

Do you see any problem with that @fernandohds564 @gu1lhermelp @jlmais ?

EDIT:

Also, the biggest issue is that it's a manual process to keep the master branch synchronized with the head of another branch

**Comment by fernandohds564** [comment]
Hi @lerwys, no, I don't see any problem with that! Actually I think it is a good idea! :smile:

**Comment by lerwys** [comment]
I'm changing the default branch to base-3.15 and tomorrow or so I will remove the master branch, then

**Comment by lerwys** [comment]
Done. Now we have 4 official branches: base-3.14, base-3.15, base-3.16 and base-7.0. The other branches are "feature branches" that should be merged back to master at some point
