### ISSUE TITLE
Ubuntu:18.04 installation option

### ISSUE THREAD

**Issue by fernandohds564** [lnls-sirius/epics-dev#7]
It would be nice to have an installation option for `ubuntu:18.04`. I tried to use this repository to install epics on `ubuntu:18.04` and I got this error message:

`E: Package 'libreadline6' has no installation candidate`

**Comment by lerwys** [comment]
Hi fernandohds564,

Thanks for the bug report. Currently I don't have an Ubuntu 18.04, so I won't be able to fix this just yet. I will try to fix this next week or so. Thanks!

Lucas

**Comment by lerwys** [comment]
This was fixed by pull requests #9 #11 #12 #13
